sonatype/helm3-charts

- nexus-repository-manager/Chart.yaml
- nexus-repository-manager/templates/deployment.yaml
When disabling persistence data the deployment failed #19
> Fix empty dir when persistence.enabled=false

- nexus-repository-manager/README.md
- nexus-repository-manager/templates/deployment.yaml
- nexus-repository-manager/templates/ingress.yaml
- nexus-repository-manager/templates/service.yaml
- nexus-repository-manager/values.yaml
Changed some things around a bit in ingress/service to support multiple container registries when the contents need to be segregated for access control.
Comments?
> #17 improve ingress/service configuration to support multiple container registries

- nexus-repository-manager/README.md
- nexus-repository-manager/templates/deployment.yaml
- nexus-repository-manager/values.yaml
```
updated:
deployment.yaml to open ports properly
values.yaml:
- to disable docker by default 
- remove unused hostDocker parameter
```
> Fix deployment.yaml to open ports properly and minor values changes.

- nexus-repository-manager/templates/NOTES.txt
There is no more host field under hostRepo and hostDocker
> Remove old fields for ingress.hostRepo and hostDocker

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/templates/deployment.yaml
- charts/nexus-iq/values.yaml
https://sonatype.zendesk.com/agent/tickets/48901
> Adding env option to IQ

- charts/nexus-repository-manager/Chart.yaml
- charts/nexus-repository-manager/templates/deployment.yaml
Probably the last one for the time being, was planning to add to the previous PR but it was merge already.
Example diff after adding/removing a property
> Restart pod on configmap changes

- charts/nexus-iq/templates/persistentVolume.yaml
- charts/nexus-iq/templates/persistentVolumeClaim.yaml
- charts/nexus-iq/values.yaml
- model closer to the NXRM definition for pv and pvc
> INT-4273 Existing claim not implemented in IQ Server helm chart

- README.md
- charts/nexus-iq/README.md
- charts/nexus-iq/templates/NOTES.txt
- charts/nexus-repository-manager/README.md
- charts/nexus-repository-manager/templates/NOTES.txt
- remove old Helm 2 specific notes
- update docs to working examples and make more consistent
> INT-4457 - Update docs on artifacthub to target helm3

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
https://issues.sonatype.org/browse/INT-5308
> INT-5308 Release IQ 117

- charts/nexus-repository-manager/README.md
default is docker.enabled=false, not true
https://github.com/sonatype/helm3-charts/issues/46
> correct docs

- .github/workflows/release.yaml
- Jenkinsfile
- Jenkinsfile-Release
Github Default Branch Migration - Helm Charts
jira: https://issues.sonatype.org/browse/INT-5497 
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5497-branch-migration/1/
> INT-5497 | Branch migration

- docs/index.md
Add docs about how to get values.yaml for customizing your install. It had been a curiosity of my own, so I documented the likely use-case.
> i-day doc update

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
- charts/nexus-repository-manager/Chart.yaml
- charts/nexus-repository-manager/values.yaml
JIRA: 
* https://issues.sonatype.org/browse/INT-6140
* https://issues.sonatype.org/browse/INT-6136
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6140-Helm-IQ-and-NRXM-release/
> INT-6140 IQ and NRXM Helm release

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
Release IQ 127
JIRA: https://issues.sonatype.org/browse/INT-6205
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6205-Helm-IQ-Release/
> INT-6205 Helm IQ release

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-6237
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6237-helm-iq-release/
> INT-6237 Helm IQ Release 128

- charts/nexus-repository-manager/Chart.yaml
- charts/nexus-repository-manager/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-6262
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6262-helm-nxrm-release/
> INT-6262 Helm NRXM Release 3.37.0

- README.md
- overview.md
Adding `overview.md` file
JIRA: https://issues.sonatype.org/browse/INT-5174
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5174-technical-documentation-improvements/1/
> INT-5174 Technical Documentation Improvements

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
bump versions for the latest IQ release
> INT-6283 IQ release

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-6322
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6322-helm-iq-release/
> INT-6322 Helm IQ Release 130

- charts/nexus-repository-manager/Chart.yaml
- charts/nexus-repository-manager/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-6338
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6338-helm-nrxm-release/
> INT-6338 Helm NRXM Release 3.37.1

- charts/nexus-iq/Chart.yaml
- charts/nexus-iq/values.yaml
JIRA: https://issues.sonatype.org/browse/INT-6373
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6373-helm-iq-release/
> INT-6373 Helm IQ Release 131

- charts/nexus-iq/README.md
- charts/nexus-iq/templates/deployment.yaml
- charts/nexus-iq/values.yaml
Team,
Added options to add Pre-created / existing PVCs for both IQ Data and Log volumes
> Added existingLogClaim support Log Volume

- docs/artifacthub-repo.yml
Now that we claimed ownership, next step is to become a verified publisher
https://issues.sonatype.org/browse/INT-6404
> INT-6404 add repo ID to be verified publisher

- charts/nexus-iq/templates/persistentVolumeClaim.yaml
don't create the log pvc when an existing log claim is specified
JIRA: https://issues.sonatype.org/browse/INT-6251
> INT-6251 skip creating a log pvc

- charts/nexus-iq/values.yaml
fixes for yamllint of nexus-iq/values.yaml. this is mostly changes to whitespace.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5705-yamllint-iq-values/
> fixes for yamllint

- charts/nexus-repository-manager/README.md
Added clarity about using the Nexus Helm versus the resiliency documentation
> Edit to Nexus Readme

- Jenkinsfile-Release
Automatically release the Jira fix version at the end of the deploy CI job. 
JIRA: https://issues.sonatype.org/browse/INT-6584
> INT-6584 Adding step to release JIRA version

- charts/nexus-iq/README.md
- charts/nexus-iq/values.yaml
provide minimum requirements in docs and as samples in values.yaml to make it easier for users to setup for a production instance.
JIRA: https://issues.sonatype.org/browse/INT-6550
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6550-prod-resources/
> INT-6550 introduce minimum required resources

- Jenkinsfile-Release
Jira: https://issues.sonatype.org/browse/INT-6614
Build: N/A
> Verify download links - INT-6614

- charts/nexus-iq/templates/deployment.yaml
- charts/nexus-iq/tests/deployment_test.yaml
- charts/nexus-iq/values.yaml
set server's user agent to represent the helm install, and upgrade to IQ 133
JIRA: https://issues.sonatype.org/browse/INT-6562
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6562-user-agent/
> INT-6562 set server user agent

- charts/nexus-iq/values.yaml
Add the keys for `initialAdminPassword` and feature enableUnauthenticatedPages
> Add initialAdminPassword and features

- Jenkinsfile-Release
- README.md
- charts/nexus-iq/templates/test/test-check-logs.yaml
- charts/nexus-iq/templates/test/test-connection.yaml
- charts/nexus-repository-manager/templates/test/test-check-logs.yaml
- charts/nexus-repository-manager/templates/test/test-connection.yaml
- charts/nexus-repository-manager/values.yaml
Updating release script to automate steps to add git tags and validate `index.yaml` on the helm repository. Additionally I am adding a couple of tests using the `"helm.sh/hook": test` hook to check chart is up and running and to check the version in the log file.
JIRA: https://issues.sonatype.org/browse/INT-6589
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6589-improve-release-script/
> INT-6589 Adding tests for connection and logs and updating release script

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
* add a pull request templatea
* mention lint in readme
* refine contributing.md to remove unnecessary steps
> update docs for contributors

- charts/nexus-iq/README.md
- charts/nexus-iq/templates/persistentVolume.yaml
- charts/nexus-iq/tests/pv_test.yaml
- charts/nexus-iq/values.yaml
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)? I work here
* Have you added and run automated tests for your change? 
```
helm3-charts/charts/nexus-iq$ helm unittest -3 -t junit -o test-output.xml .
PASS  deployment       tests/deployment_test.yaml
PASS  ingress  tests/ingress_test.yaml
PASS  persistentVolume tests/pv_test.yaml
Charts:      1 passed, 1 total
Test Suites: 3 passed, 3 total
Tests:       10 passed, 10 total
Snapshot:    0 passed, 0 total
Time:        41.381095ms
```
* Have you run `helm lint` on your change?
```
helm3-charts/charts/nexus-iq$ helm lint
==> Linting .
1 chart(s) linted, 0 chart(s) failed
```
> Adding more storage options and affinity to persistentVolumes

- charts/nexus-iq/README.md
- charts/nexus-iq/templates/persistentVolume.yaml
- charts/nexus-iq/tests/pv_test.yaml
- charts/nexus-iq/values.yaml
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)? I work here
* Have you added and run automated tests for your change?
```
helm3-charts/charts/nexus-iq$ helm unittest -3 -t junit -o test-output.xml .
PASS  deployment       tests/deployment_test.yaml
PASS  ingress  tests/ingress_test.yaml
PASS  persistentVolume tests/pv_test.yaml
Charts:      1 passed, 1 total
Test Suites: 3 passed, 3 total
Tests:       10 passed, 10 total
Snapshot:    0 passed, 0 total
Time:        46.990488ms
```
* Have you run `helm lint` on your change?
```
helm3-charts/charts/nexus-iq$ helm lint
==> Linting .
1 chart(s) linted, 0 chart(s) failed
```
> separate csi config for data and logs

- upgrade.sh
This replaces step 1 of the upgrade steps where we apply these versions by hand.
`./upgrade.sh charts/nexus-iq 136.0.0 1.136.0`
Sample execution:
```
$ ./upgrade.sh charts/nexus-repository-manager 39.0.0 3.39.0
diff --git a/charts/nexus-repository-manager/Chart.yaml b/charts/nexus-repository-manager/Chart.yaml
index fa0da1c..cb6c4cb 100644
--- a/charts/nexus-repository-manager/Chart.yaml
+++ b/charts/nexus-repository-manager/Chart.yaml
@@ -3,10 +3,10 @@ name: nexus-repository-manager
-version: 38.1.0
+version: 39.0.0
-appVersion: 3.38.1
+appVersion: 3.39.0
description: Sonatype Nexus Repository Manager - Universal Binary repository
diff --git a/charts/nexus-repository-manager/values.yaml b/charts/nexus-repository-manager/values.yaml
index 4299cd8..05963a6 100644
--- …
```
> script to automate the update for upgrading a server

- charts/nexus-iq/templates/_helpers.tpl
Fix formatting of the dictionary for the terraform parser.
> Change format for the terraform parser.

- README.md
- charts/nexus-repository-manager/.helmignore
- charts/nexus-repository-manager/Chart.yaml
- charts/nexus-repository-manager/LICENSE
- charts/nexus-repository-manager/README.md
- charts/nexus-repository-manager/templates/NOTES.txt
- charts/nexus-repository-manager/templates/_helpers.tpl
- charts/nexus-repository-manager/templates/configmap-properties.yaml
- charts/nexus-repository-manager/templates/configmap.yaml
- charts/nexus-repository-manager/templates/deployment.yaml
- charts/nexus-repository-manager/templates/ingress.yaml
- charts/nexus-repository-manager/templates/proxy-route.yaml
- charts/nexus-repository-manager/templates/pv.yaml
- charts/nexus-repository-manager/templates/pvc.yaml
- charts/nexus-repository-manager/templates/route.yaml
- charts/nexus-repository-manager/templates/secret.yaml
- charts/nexus-repository-manager/templates/service.yaml
- charts/nexus-repository-manager/templates/serviceaccount.yaml
- charts/nexus-repository-manager/templates/test/test-check-logs.yaml
- charts/nexus-repository-manager/templates/test/test-connection.yaml
- charts/nexus-repository-manager/tests/deployment_test.yaml
- charts/nexus-repository-manager/tests/ingress_test.yaml
- charts/nexus-repository-manager/values.yaml
- overview.md
Bring back the old charts for NXRM 3, so we can release updates until the new charts are ready.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/restore-nxrm/
> Restore nxrm

- charts/nexus-repository-manager/tests/deployment_test.yaml
add a test for securityContext values.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/test-existing-securityContext/
> boyscout: add missing test for securityContext

- README.md
Added note to Readme pointing to new NXRM Helm Repo
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)?
* Have you added and run automated tests for your change? 
* Have you run `helm lint` on your change?
> NEXUS-35079 - Update Readme for New NXRM Helm Repo

- Jenkinsfile-Release
Updating Jenkins job in order to reorganize arifacts generation. [Jira ticket](https://issues.sonatype.org/browse/NEXUS-34974) for reference
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)?
* Have you added and run automated tests for your change? No changes in helm itself
* Have you run `helm lint` on your change? No changes in helm itself
> NEXUS-34974 Publish nxrm helm charts to Sonatype helm repo and Artifact Hub

- Dockerfile
upgrade to latest helm.
JIRA: https://issues.sonatype.org/browse/INT-7384
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-7384-helm-3.10.1/
> INT-7384 helm 3.10.1

- charts/nexus-iq/tests/deployment_test.yaml
- charts/nexus-iq/values.yaml
apply securityContext to the container to alleviate warnings in openshift.
JIRA: https://issues.sonatype.org/browse/INT-7432
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-7432-security-for-new-k8s-openshift/
> INT-7432 security for new k8s and openshift

- Dockerfile
JIRA: https://issues.sonatype.org/browse/INT-7467
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-7467-helm-upgrade/
> upgrade to helm 3.10.2

- Jenkinsfile-Release
Jira: https://issues.sonatype.org/browse/CLM-23705
> CLM-23705 - Update CI jobs to point to CLM project

- charts/nexus-iq/templates/deployment.yaml
- charts/nexus-iq/values.yaml
Add an environment label that can be used for datadog and other settings.
> CO-8 Add an environment label

- Jenkinsfile-Release
* Have you added and run automated tests for your change? 
* Have you run `helm lint` on your change?
> remove resiliency chart from publish

- Jenkinsfile-Release
Changes to allow deprecation of old nexus repo helm charts
> NEXUS-40550-Allow publishing of deprecated charts

- Jenkinsfile-Release
Reverts sonatype/helm3-charts#285
> Revert "NEXUS-40550-Allow publishing of deprecated charts"

- Jenkinsfile-Release
Reverts sonatype/helm3-charts#286
> Revert "Revert "NEXUS-40550-Allow publishing of deprecated charts""

- Jenkinsfile-Release
Reverts sonatype/helm3-charts#287
Finally reverting back to the original setting now that we have deprecated the old nexus charts
> Revert "Revert "Revert "NEXUS-40550-Allow publishing of deprecated charts"""

- Jenkinsfile-Release
Fixes the tagging section of the jenkins script for the ha helm chart
> Fix jenkins file for helm3 charts

- Jenkinsfile-Release
Fix to use the correct version for the tag
> Fix jenkins
