nexus-repository-manager/templates/ingress.yaml
Currently there is no way to use custom Ingress resources with your own domain. This PR fixes this behavior by implementing correct parsing of the ingress.hosts key from the values.yaml
=> Fixed creation of invalid Ingress resource

nexus-repository-manager/templates/deployment.yaml, nexus-repository-manager/templates/service.yaml
The docker ingress resource was missing the appropriate ports in the deployment and service. This commit adds them.
=> Added default docker ports for the deployment and service

nexus-repository-manager/README.md
The empty line in the table was causing the Markdown to not render correctly and making it hard to read some settings. This should fix it.
=> Fix Markdown table rendering bug

charts/nexus-repository-manager/Chart.yaml, charts/nexus-repository-manager/README.md, charts/nexus-repository-manager/templates/configmap-properties.yaml, charts/nexus-repository-manager/templates/deployment.yaml, charts/nexus-repository-manager/values.yaml
Proof that it works :) 
Also, I've used a map for configmap in case someone keeps a separate `values-sercrets.yaml` file, so secret values for nexus properties can be merged with non-secret ones. And the only thing that may be secret there (I think) is ldap credentials:
And seems like they can be set in nexus.properties according to this [article](https://support.sonatype.com/hc/en-us/articles/216597138-Setting-Advanced-LDAP-Connection-Properties-in-Nexus-Repository-Manager) but I haven't tested myself
And one more note, I could not find how current configmap setup is used, so created a separate one to avoid potential breaking changes. The same approach could be used later for other configuration files like `nexus.vmoptions` if anyone needs it.
=> Fixes sonatype/helm3-charts#21

charts/nexus-repository-manager/Chart.yaml
Issue #39 was cause by a PR that created the chart version 29.1.0 which I missed. I deleted the package here on GH thinking it would get removed. this is about when I noticed our index file wasn't being updated by the chart releaser.
Releasing charts...
Using config file:  /home/runner/work/helm3-charts/helm3-charts/cr.yaml
Updating charts repo index...
Using config file:  /home/runner/work/helm3-charts/helm3-charts/cr.yaml
Using existing index at .cr-index/index.yaml
Found nexus-repository-manager-29.0.2.tgz
Extracting chart metadata from .cr-release-packages/nexus-repository-manager-29.0.2.tgz
Calculating Hash for .cr-release-packages/nexus-repository-manager-29.0.2.tgz
Updating index .cr-index/index.yaml
look for another PR to fix the index
=> republish  29.1.0

charts/nexus-iq/Chart.yaml, charts/nexus-iq/values.yaml
Upgrading looks pretty easy now. This is the IQ 105 release for helm3 charts.
JIRA: https://issues.sonatype.org/browse/INT-4387
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-4387-upgrade-iq-105/
=> upgrade to IQ 1.105.0

CONTRIBUTING.md, README.md
Attempt to define an initial contributors guide. There do not appear to be many corporate guidelines beyond ensuring that all contributors must sign the CLA https://sonatypecla.herokuapp.com/sign-cla and that we have a license defined (already in place).
Jira: https://issues.sonatype.org/browse/INT-4185
=> Initial contributing.md

charts/nexus-iq/templates/deployment.yaml, charts/nexus-iq/templates/persistentVolume.yaml, charts/nexus-iq/templates/persistentVolumeClaim.yaml, charts/nexus-iq/values.yaml
IQ 113 Docker Image have introduced start.sh script that stores stderr to /var/log/nexus-iq-server and adds the volume.
Added PVC / PV for log volume in Helm chart, to fix the below error during helm deployment.
`./start.sh: line 1: /var/log/nexus-iq-server/stderr.log: Permission denied`
Also enabled IQ loggers to use the log files in log volume
=> Added log volume and logging for IQ 113

charts/nexus-repository-manager/templates/NOTES.txt, charts/nexus-repository-manager/values.yaml
Updating serviceType to type on:
* I updated `values.yaml` 
* I found some extra references in `templates/NOTES.txt`. Without the change on this file, I am not able to create the helm using `helm install nrxm charts/nexus-repository-manager`
When installing helm and checking logs, everything looks good:
JIRA: https://issues.sonatype.org/browse/INT-5470
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5470-serviceType-should-be-type/
=> INT-5470 Updating serviceType to type

charts/nexus-iq/values.yaml
License unable to be automatically installed via Helm deployment
Jira:  https://issues.sonatype.org/browse/INT-5549  
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5549-license-automatically-installed/1/
=> INT-5549 | License unable to be automatically installed via Helm deployment

Jenkinsfile-Release
This PR is to solve an intermittent issue on the release build for Helm Charts. 
Check this build error:
- https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Main%20Release%20Build/47/
And this Slack thread:
- https://sonatype.slack.com/archives/CCBVDFPJA/p1640105681210700
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/removing-git-global-config/
=> INT-6373 Removing global flag on git commands for deploy stage

docs/artifacthub-repo.yml
First step towards creating a verified publisher is claiming the repository. We do that by creating an `artifact-repo.yml` file which lists the owners. The owners must include the list of emails which will be used to log into artifacthub.io. Rather than attempt to create a dummy account and deal with sharing passwords, adding all team members.
https://issues.sonatype.org/browse/INT-6404
=> INT-6404 add owners in order to claim repository

charts/nexus-iq/README.md, charts/nexus-iq/templates/deployment.yaml, charts/nexus-iq/values.yaml
Making `sonatype-work` string common for `values.yaml` and `deployment.yaml`
JIRA: https://issues.sonatype.org/browse/INT-6161
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6161-remove-sonatype-work-unused-env-var/
=> INT-6161 Making sonatype-work string common

charts/nexus-repository-manager/README.md, charts/nexus-repository-manager/values.yaml
Signed-off-by: Yuval Manor yuvalman958@gmail.com
Resolves #96 
The env var install4jAddVmParams does not exist in the nexus image.
Instead, the env var that should be used is INSTALL4J_ADD_VM_PARAMS.
We can see in the attached screenshot that only after adding the INSTALL4J_ADD_VM_PARAMS env var, the params of the jvm process in the nexus container was changed to the right values.
=> fix: use the right jvm params env var: INSTALL4J_ADD_VM_PARAMS

charts/nexus-iq/README.md, charts/nexus-iq/templates/deployment.yaml, charts/nexus-iq/values.yaml
Adding config options for liveness and readiness probes:
* I have updated the `deployment.yaml` template to add the new configuration options
* I have updated the `values.yaml` with the default values for the new configuration options
* I have updated the `README.md` file to add the new configuration options
JIRA: https://issues.sonatype.org/browse/INT-6416
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6416-adding-liveness-readiness-options/
=> INT-6416 Adding config options for liveness and readiness probes

charts/nexus-repository-manager/README.md
The existing directions were backward and lacked details of the alternative fixed login/password.
=> document random vs fixed passwords better

charts/nexus-iq/README.md, charts/nexus-iq/templates/NOTES.txt, charts/nexus-iq/templates/ingress.yaml, charts/nexus-iq/tests/ingress_test.yaml, charts/nexus-iq/values.yaml
update Ingress to v1 for IQ.
JIRA: https://issues.sonatype.org/browse/INT-5705
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5705-upgrade-beta-apis-for-iq/
=> INT-5705 upgrade beta apis for iq

charts/nexus-repository-manager/templates/deployment.yaml, charts/nexus-repository-manager/tests/deployment_test.yaml, charts/nexus-repository-manager/values.yaml
To alleviate the need for the deprecated PodSecurityPolicy, set and document the default securityContext on the pod.
Also a bit of formatting cleanup.
JIRA: https://issues.sonatype.org/browse/INT-5705
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5705-set-securityContext-to-match-container/
=> INT-5705 set security context to match container

charts/nexus-iq/templates/ingress.yaml, charts/nexus-iq/tests/ingress_test.yaml, charts/nexus-iq/values.yaml, charts/nexus-repository-manager/templates/ingress.yaml, charts/nexus-repository-manager/tests/ingress_test.yaml, charts/nexus-repository-manager/values.yaml
Switch from older ingress.class annotation to newer standard ingressClassName.  This continues to work in docker desktop like the annotation did.
JIRA: https://issues.sonatype.org/browse/INT-6531
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6531-ingressClassName/
=> INT-6531 switch to newer ingressClassName

charts/nexus-iq/README.md, charts/nexus-iq/values.yaml
Didn't work. Use JAVA_OPTS instead if you want to configure memory in a meaningful way.
JIRA: https://issues.sonatype.org/browse/INT-5720
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-5720-unused-iq-memory/
=> INT-5720 remove unused iq.memory setting

README.md, charts/nexus-iq/README.md, charts/nexus-iq/tests/ingress_test.yaml, charts/nexus-iq/values.yaml, charts/nexus-repository-manager/tests/ingress_test.yaml, charts/nexus-repository-manager/values.yaml
Apply an nginx annotation to remove the limit of upload size, which is often needed for nxrm and for iq.
JIRA: https://issues.sonatype.org/browse/INT-6585
Bulid: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6585-upload-limits/
=> INT-6585 upload limits

charts/nexus-repository-manager/templates/ingress.yaml, charts/nexus-repository-manager/tests/ingress_test.yaml, charts/nexus-repository-manager/values.yaml
* add the ingressClassName to the docker ingress like it was to the repo ingress.
* some small cleanups
* extra tests around ingress
JIRA: https://issues.sonatype.org/browse/INT-6696
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6696-docker-ingressClassName/
I'm still putting together a proper plan to test docker repo end-to-end. It is provably listening now, but I need to work around certificates, since it's TLS.
=> INT-6696 docker ingress class name

charts/nexus-repository-manager/tests/deployment_test.yaml, charts/nexus-repository-manager/values.yaml
set javaprefs to /nexus-data so the license is preserved across restarts of the pod.
JIRA: https://issues.sonatype.org/browse/INT-6828
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6828-preserve-license/
=> INT-6828 add javaprefs into OPTS to preserve license across restarts

Dockerfile
upgrade test docker image to use helm 3.9.0
JIRA: https://issues.sonatype.org/browse/INT-6852
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-6852-helm-3.9.0/
=> INT-6852 use helm 3.9.0 for tests

Jenkinsfile-Release, build.sh
NXRM team is taking over the nxrm chart with their own [repo](https://github.com/sonatype/nxrm3-helm-repository) and have removed the chart from this repo, so this PR removes it the rest of the way from the build.
Build: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/remove-nxrm-from-build/
=> remove references to nxrm from build

charts/nexus-iq/templates/_helpers.tpl
Terraform was returning with an error: unclosed action. This changes the format from multiline to single line to make terraform happy.
Jira: https://issues.sonatype.org/browse/CLM-22042
Jenkins: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/fix-formatting-for-terraform-2/
=> Fix formatting for terraform parse error

docs/index.md
NEXUS-34129 involves publishing the aws resiliency helm chart located in nxrm3-helm-repository to artifact hub. This change updates the index.md to include information about the aforementioned helm chart.
=> NEXUS-34129 - Include information about the resiliency helm charts located in  nxrm3-helm-repository

Dockerfile
Adding Helm version 3.10.0 to Docker file in order to check Helm Charts compatibility.
https://issues.sonatype.org/browse/INT-7315
https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/INT-7315_Helm_charts_compatibility_Helm3.10.0/3/
=> INT-7315 Adding recent version of Alpine Helm 3.10.0

Jenkinsfile-Release
This includes the new nexus-iq-server-HA helm chart in to the chart release cycle. The chart is currently hosted/maintained in https://github.com/sonatype/nexus-iq-server-ha/tree/main/chart. 
**NOTE:**
The repository above is still not public (we will be making it public along with the official HA release). So until then, plan is to keep this PR as a DRAFT (not to publish the chart yet to artifacthub)
=> Include nexus-iq-server-ha helm chart in to the release - CLM-23674

build-iq.sh
-3 flag was removed in the latest version of the unittest plugin which is breaking builds in test stage. Simply removing the flag `-3` caused some tests to fail. Pinning the plugin version seems to make the build green: https://jenkins.ci.sonatype.dev/job/integrations/job/cloud/job/Helm3%20Charts/job/Feature%20Snapshot%20Builds/job/fix-build-use-fixed-version-unittest-plugin/
I did run `helm lint` on my branch however it was not successful:
```
> helm lint
==> Linting .
Error unable to check Chart.yaml file in chart: stat Chart.yaml: no such file or directory
Error: 1 chart(s) linted, 1 chart(s) failed
```
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)?
* Have you added and run automated tests for your change? 
(See the …
=> Pin unittest plugin version to 0.2.11

Jenkinsfile-Release
Update the path from which the nexus repo ha helm charts are grabbed from. This is in correlation with PR: https://github.com/sonatype/nxrm3-ha-repository/pull/21
=> update path for nexus repo ha helm chart

charts/nexus-iq/templates/deployment.yaml, charts/nexus-iq/tests/deployment_test.yaml, charts/nexus-iq/values.yaml
Add startup probe to iq server pod
* Have you signed the [Sonatype CLA](https://sonatypecla.herokuapp.com/sign-cla)?  :white_check_mark: 
* Have you added and run automated tests for your change?   :white_check_mark: 
* Have you run `helm lint` on your change? :white_check_mark:
=> Add startup probe to iq server pod - CLM-26122
